def calc(a,b):
    return a/b

try:
    print(calc(40,0))
except Exception as e:
    print("error", e)